[project]
name = "jejuchat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.9.0",
    "google-generativeai>=0.8.3",
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "streamlit>=1.39.0",
    "torch>=2.4.1",
    "transformers>=4.45.2",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.9",
]
